// <auto-generated />
namespace PlateformeAnnonceBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addfavoris : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfavoris));
        
        string IMigrationMetadata.Id
        {
            get { return "201903280724515_addfavoris"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
